# -*- Makefile -*-

# Set the name of the project here
PROJECT_NAME := KLEE
PROJ_VERSION := 1.2.0

# Set this variable to the top of the LLVM source tree.
LLVM_SRC_ROOT = /home/sanghu/TracerX/llvm

# Set this variable to the top level directory where LLVM was built
# (this is *not* the same as OBJ_ROOT as defined in LLVM's Makefile.config).
LLVM_OBJ_ROOT = /home/sanghu/TracerX/llvm

LLVM_VERSION_MAJOR = 3
LLVM_VERSION_MINOR = 4

# Set this to the build mode used to build LLVM (not necessarily the same
# as the build mode used for KLEE)
LLVM_BUILD_MODE = Release

# Set the directory root of this project's source files
PROJ_SRC_ROOT := $(subst //,/,/home/sanghu/TracerX/tracerx)

# Set the root directory of this project's object files
PROJ_OBJ_ROOT := $(subst //,/,/home/sanghu/TracerX/tracerx)

# Set the root directory of this project's install prefix
PROJ_INSTALL_ROOT := /usr/local

KLEE_USE_CXX11 := 0

ENABLE_STP := 1
STP_CFLAGS := -I/home/sanghu/TracerX/stp/build/include
STP_LDFLAGS := -L/home/sanghu/TracerX/stp/build/lib -lstp -lminisat

Z3_CFLAGS := -I/home/sanghu/TracerX/z3/build/include
Z3_LDFLAGS := -L/home/sanghu/TracerX/z3/build/lib -lz3

ENABLE_METASMT := 0
METASMT_ROOT := 
METASMT_DEFAULT_BACKEND := 

ENABLE_Z3 := 1
Z3_CFLAGS := -I/home/sanghu/TracerX/z3/build/include
Z3_LDFLAGS := -L/home/sanghu/TracerX/z3/build/lib -lz3

ENABLE_POSIX_RUNTIME := 1
ENABLE_UCLIBC := 1

KLEE_UCLIBC_BCA := /home/sanghu/TracerX/klee-uclibc/lib/libc.a

HAVE_SELINUX := 0

HAVE_TCMALLOC := 1
TCMALLOC_LIB := -ltcmalloc_minimal

HAVE_ZLIB := 1

RUNTIME_ENABLE_OPTIMIZED := 1
RUNTIME_DISABLE_ASSERTIONS := 0
RUNTIME_DEBUG_SYMBOLS := 
RUNTIME_ENABLE_COVERAGE :=
RUNTIME_ENABLE_PROFILING :=

# Compilers used to build runtime library and run tests
KLEE_BITCODE_C_COMPILER := /home/sanghu/TracerX/llvm/Release/bin/clang
KLEE_BITCODE_CXX_COMPILER := /home/sanghu/TracerX/llvm/Release/bin/clang++

# Host compiler
KLEE_HOST_C_COMPILER := gcc
KLEE_HOST_CXX_COMPILER := g++

# A list of "features" which tests can check for in XFAIL:
TEST_FEATURE_LIST :=

ifeq ($(HAVE_SELINUX_SELINUX_H),1)
  TEST_FEATURE_LIST += have-selinux
else
  TEST_FEATURE_LIST += no-selinux
endif

# disable unwind test
TEST_FEATURE_LIST += no-unwind

CFLAGS := -g -O2 -Wall -g
CXXFLAGS := -g -O2 -g -Wall
LDFLAGS := -L/home/sanghu/TracerX/minisat/build/release/lib/ -g

REQUIRES_RTTI := 0
